### PR TITLE
Added parameter '-s' to specify the server address

### PR DESCRIPTION
**Pull request by yukra**
I run ntpd on ipv4 only, and ntpstat tries to connect via ipv6-address ::1. I added the '-s' parameter to tell ntpstat to connect to 127.0.0.1. Also, in this parameter you can specify the path to the socket for chronyd.

### CODE REVIEW

**Comment by mlichvar** [comment]
Instead of allowing any address to be specified, I think I'd prefer `-4` and `-6` options, which would set the hostname directly to 127.0.0.1 and ::1 respectively, or some automatic discovery which would try both and see what works.

**Comment by yukra** [comment]
I removed the '-s' parameter and added '-4' and '-6'.

**Comment by mlichvar** [comment]
I implemented an automatic detection, so users don't have to investigate why it doesn't work. Can you please try the latest code and see if it works for you?

**Comment by yukra** [comment]
New version works good, thx.

**Pull request closed without merging**
